name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-mod:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: build mod
        working-directory: mod
        run: dotnet build -c Release

      - name: upload mod DLL
        uses: softprops/action-gh-release@v2
        with:
          files: mod/bin/Release/net472/SpinDataRelay.dll
